### ISSUE TITLE
[Question] Homework 1: test thread_pool_drop_propogate_panic

### ISSUE THREAD

**Issue by A-Mehdi** [kaist-cp/cs492-concur#129]
I have passed other cases in thread_pool except for thread_pool_drop_propogate_panic. When I run the test case, I get the following error.
```
thread '<unnamed>' panicked at 'explicit panic', src/hello_server/thread_pool.rs:209:13thread '
<unnamed>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/hello_server/thread_pool.rs:84:42
thread 'thread '<unnamed>' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', called `Result::unwrap()` on an `Err` value: RecvErrorsrc/hello_server/thread_pool.rs', :src/hello_server/thread_pool.rs84::8442:
42
test hello_server::thread_pool::test::thread_pool_drop_propagate_panic ... FAILED
```
It panics but it does not pass the test case. I think it is because the channel is disconnected, I get RecvError, but when the sender is not dropped, it hangs. What is the problem here?

**Comment by tomtomjhj** [comment]
I'm not entirely sure what's going on but I guess you're unconditionally unwrapping the recv result, which can be problematic when the channel gets disconnected.

**Comment by jeehoonkang** [comment]
Closing for inactivity; please reopen this issue if you have further questions.
