### ISSUE TITLE
[Question] Homework3 thread panic 

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#159]
While dealing with the Homework3, I suddenly got error on all test that looks like this:

```
running 5 tests

test correctness::clone_drop_atomic ... thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/arc.rs:245:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
test correctness::count_sync ... thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 94645723410720', /home/s20160325/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.6/src/rt/object.rs:361:25
FAILED
test correctness::drop_sync ... thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 94645723410784', /home/s20160325/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.6/src/rt/object.rs:361:25
FAILED
test correctness::get_mut_sync ... thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 94645723386320', /home/s20160325/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.6/src/rt/object.rs:361:25
FAILED
test correctness::try_unwrap_sync ... thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 94645723386688', /home/s20160325/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.6/src/rt/object.rs:361:25
FAILED

...
```
I ran `cargo test --features check-loom --test arc -- --nocapture --test-threads 1` test. I don't understand what kind of error this is, which makes some kind of length 3 to a enormous number. Is there anyone who got the same problem?

**Comment by tomtomjhj** [comment]
"index out of bounds" errors from check-loom test are probably related to memory reclamation. First, focus on `clone_drop_atomic` failure. The error message says that there is an interleaving of instructions in which the canary is not dropped.
