### ISSUE TITLE
[Question] remote ssh can't connect - Server installation process already in progress

### ISSUE THREAD

**Issue by Electric-Tunnel** [kaist-cp/cs492-concur#190]
```
[17:22:01.217] > s20203613@cp-service.kaist.ac.kr's password: 
[17:22:01.218] Showing password prompt
[17:22:03.487] Got password response
[17:22:03.488] "install" wrote data to terminal: "**********"
[17:22:03.501] > 
> 
[17:22:03.578] > 59b642484fb3: running
> 
[17:22:03.609] > Acquiring lock on /home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7
> 067f125afd80a/vscode-remote-lock.s20203613.d2e414d9e4239a252d1ab117bd7067f125afd
> 80a
> 
[17:22:03.617] > Installation already in progress...
> 59b642484fb3##24##
```

After the server is up, I can't connect to server even if I enter my password right with above error message. What should I do to connect ssh server with vs code?

**Comment by jeehoonkang** [comment]
I suggest you to:

- Connect to the server via ssh;
- Remove `~/.vscode`; and
- Relaunch your vscode.

**Comment by Electric-Tunnel** [comment]
```
[22:39:42.970] > Server did not start successfully. Full server log at /home/s20203613/.vscode-se
> rver/.d2e414d9e4239a252d1ab117bd7067f125afd80a.log >>>
> Error: Cannot find module 'minimist'
> Require stack:
> - /home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/ou
> t/bootstrap-amd.js
> - /home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/ou
> t/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067
> f125afd80a/out/vs/loader.js:17:960)
>     at e.load (/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067
> f125afd80a/out/vs/loader.js:13:941)
>     at o (/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125a
> fd80a/out/vs/loader.js:31:189)
>     at Object.errorback (/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1a
> b117bd7067f125afd80a/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d
> 1ab117bd7067f125afd80a/out/vs/loader.js:14:306)
>     at /home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd8
> 0a/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/home/s20203613/.vscode-server/bin/d2e414d9e423
> 9a252d1ab117bd7067f125afd80a/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a
> /out/bootstrap-amd.js',
>     '/home/s20203613/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a
> /out/vs/server/main.js'
>   ],
( ... )
> <<< End of server log
```
Thank you for answering but I still have some problems.
I just remove .vscode and .vscode-server but I can't connect to server with above error message. Actually, I can't remove .vscode-server because it is busy. This is error message when I just try to remove .vscode-server:
```
rm: cannot remove '.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/.nfs000000000138040100000007': Device or resource busy
rm: cannot remove '.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node_modules/spdlog/build/Release/.nfs000000000122071a00001436': Device or resource busy
rm: cannot remove '.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/.nfs000000000122139e00001437': Device or resource busy
rm: cannot remove '.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/.nfs000000000122139c00001439': Device or resource busy
rm: cannot remove '.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/.nfs00000000013a136a00001438': Device or resource busy
rm: cannot remove '.vscode-server/data/logs/20201102T015059/.nfs0000000001380481000019bf': Device or resource busy
rm: cannot remove '.vscode-server/.nfs00000000012211ad000019c0': Device or resource busy
```
Could you tell me what I should do please?

**Comment by jeehoonkang** [comment]
I moved your `.vscode-server` to `.vscode-server-old-delete-me`.  Now you can connect with vscode, I gues.
