### ISSUE TITLE
[Question] homework4, Running cargo asan for one test

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#214]
Hi, I am working with cargo_asan to check segmentation fault, but it just tells me that thread panicked at 'not implemented'. I checked that the address sanitizer for list_set invoked segmentation fault, and it reported that thread smoke allocated and freed the used-after-freed address. Thus I tried running the smoke test, which gave me no information about the segmentation fault. I wonder if it is a wrong way to detect segmentation fault. Is it detecting another kind of error? I will appreciate any help.

'''
running 1 test
test art_smoke ... FAILED

failures:

---- art_smoke stdout ----
thread 'art_smoke' panicked at 'not implemented', /home/s20160325/cs492-concur/homework/src/art/mod.rs:116:9
stack backtrace:
   0:     0x55b241904e80 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x55b241904e80 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b241904e80 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b241904e80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b24192837c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/core/src/fmt/mod.rs:1078:17
   5:     0x55b241741076 - std::io::Write::write_fmt::h4e66e5913c94a188
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/io/mod.rs:1518:15
   6:     0x55b2418ff14d - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h422b0eaf06f09c5c
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/io/impls.rs:179:9
   7:     0x55b241907555 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:49:5
   8:     0x55b241907555 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:36:9
   9:     0x55b241907555 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:208:50
  10:     0x55b2419071a2 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:224:9
  11:     0x55b241907cf1 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:593:17
  12:     0x55b2418d622e - std::panicking::begin_panic::{{closure}}::h7a442f4158969faf
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:522:9
  13:     0x55b2418d92fc - std::sys_common::backtrace::__rust_end_short_backtrace::hf9f6068bded45f2f
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x55b2418d5a60 - std::panicking::begin_panic::he3d45c2f28972fbe
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:521:12
  15:     0x55b241700c83 - cs492_concur_homework::art::Art<V>::cursor::h6643cf9426fba401
                               at /home/s20160325/cs492-concur/homework/src/art/mod.rs:116:9
  16:     0x55b2417003af - cs492_concur_homework::art::Art<V>::entry::h1ec1d08b72182347
                               at /home/s20160325/cs492-concur/homework/src/art/mod.rs:125:22
  17:     0x55b2416fe9fc - <cs492_concur_homework::art::Art<V> as cs492_concur_homework::map::SequentialMap<str,V>>::insert::h0960090e65f9ac07
                               at /home/s20160325/cs492-concur/homework/src/art/mod.rs:133:9
  18:     0x55b2416cea38 - art::art_smoke::h72687284c86d5e70
                               at /home/s20160325/cs492-concur/homework/tests/art.rs:8:13
  19:     0x55b24170a46a - art::art_smoke::{{closure}}::h999557960a265186
                               at /home/s20160325/cs492-concur/homework/tests/art.rs:6:1
  20:     0x55b2416e5525 - core::ops::function::FnOnce::call_once::h5f00f28f5eb27cbd
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/core/src/ops/function.rs:227:5
  21:     0x55b241768bb3 - core::ops::function::FnOnce::call_once::h5a2d5be79dfbb3fa
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/core/src/ops/function.rs:227:5
  22:     0x55b241768bb3 - test::__rust_begin_short_backtrace::hc37895a957a28819
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/test/src/lib.rs:517:5
  23:     0x55b24176706a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2e984eb76fd48d18
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/alloc/src/boxed.rs:1307:9
  24:     0x55b24176706a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0f6b5d488d670cea
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panic.rs:322:9
  25:     0x55b24176706a - std::panicking::try::do_call::hdb3aa512bebe10c5
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:381:40
  26:     0x55b24176706a - std::panicking::try::h1f092055c90b1f8d
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:345:19
  27:     0x55b24176706a - std::panic::catch_unwind::h8375af0e881b2e9d
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panic.rs:396:14
  28:     0x55b24176706a - test::run_test_in_process::h9e242243958ffdec
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/test/src/lib.rs:544:18
  29:     0x55b24176706a - test::run_test::run_test_inner::{{closure}}::h7f9bd315f38b7711
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/test/src/lib.rs:450:39
  30:     0x55b2417403f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e54559d2b0f16a3
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys_common/backtrace.rs:125:18
  31:     0x55b2417453b3 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h62061069a95aaa9f
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/thread/mod.rs:474:17
  32:     0x55b2417453b3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he3019c7097afe41c
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panic.rs:322:9
  33:     0x55b2417453b3 - std::panicking::try::do_call::ha6540e5a4210d091
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:381:40
  34:     0x55b2417453b3 - std::panicking::try::hfedf722228165384
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panicking.rs:345:19
  35:     0x55b2417453b3 - std::panic::catch_unwind::h2c7da1641a28a7b1
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/panic.rs:396:14
  36:     0x55b2417453b3 - std::thread::Builder::spawn_unchecked::{{closure}}::h87a388d10abb1211
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/thread/mod.rs:473:30
  37:     0x55b2417453b3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h577cb68fc0fa7bbe
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/core/src/ops/function.rs:227:5
  38:     0x55b24190e4fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/alloc/src/boxed.rs:1307:9
  39:     0x55b24190e4fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/alloc/src/boxed.rs:1307:9
  40:     0x55b24190e4fa - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/5404efc28a0cddee103ef6396c48ea71ff9631c8/library/std/src/sys/unix/thread.rs:89:17
  41:     0x7f08f8394609 - start_thread
  42:     0x7f08f816c293 - clone
  43:                0x0 - <unknown>

failures:
    art_smoke

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 4 filtered out

error: test failed, to rerun pass '--test art'
'''

**Comment by mickowale** [comment]
I think the test your ran is not from homework 4. The test with a similar name for homework 4 is just "smoke". 
Try running the test like this instead.
`RUSTFLAGS="-Z sanitizer=address"  cargo +nightly test  --target x86_64-unknown-linux-gnu --test list_set -- smoke`

**Comment by tomtomjhj** [comment]
:art:

**Comment by Lee-Janggun** [comment]
The message states that the failed test is `art_smoke`. These are test cases of the previous year's assignments, so will fail surely.

**Comment by haeeun-14** [comment]
Oh yes, it works now. Thank you for the help!
